[font]
size = 10.0

[font.bold]
family = "Monoid"
style = "Bold"

[font.bold_italic]
family = "Monoid"
style = "Bold Italic"

[font.italic]
family = "Monoid"
style = "Italic"

[font.normal]
family = "Monoid"
style = "Regular"
